import { db } from "@/db";
import { devices, rooms, scenes, activityLogs, wallSettings } from "@/db/schema";
import { count } from "drizzle-orm";

export async function ensureDatabaseSeeded() {
  try {
    const [deviceCount] = await db.select({ value: count() }).from(devices);
    if (deviceCount && Number(deviceCount.value) > 0) {
      return; // already seeded
    }

    // Seed Rooms
    await db.insert(rooms).values([
      { id: "all", name: "All Devices", icon: "LayoutGrid", sortOrder: 0 },
      { id: "living_room", name: "Living Room", icon: "Sofa", sortOrder: 1 },
      { id: "bedroom", name: "Master Bedroom", icon: "BedDouble", sortOrder: 2 },
      { id: "kitchen", name: "Kitchen & Dining", icon: "UtensilsCrossed", sortOrder: 3 },
      { id: "balcony", name: "Balcony & Terrace", icon: "Flower2", sortOrder: 4 },
      { id: "entrance", name: "Entrance & Security", icon: "Shield", sortOrder: 5 },
    ]);

    // Seed Wall Settings
    await db.insert(wallSettings).values({
      id: "default_panel",
      panelName: "Tuya Smart Control Panel T6E",
      theme: "midnight",
      tempUnit: "C",
      screenSaverTimeout: 60,
      screenSaverType: "digital_clock",
      soundFeedback: true,
      kioskScale: 100,
      lockPin: "1234",
      tuyaAccessId: "",
      tuyaAccessSecret: "",
      tuyaEndpoint: "https://openapi.tuyaus.com",
      // Big top-bar quick controls. Groups resolve by category so every AC or
      // every shutter can be operated with one tap.
      favorites: [
        {
          id: "fav_all_ac",
          label: "All ACs",
          icon: "AirVent",
          gradient: "from-cyan-500 to-blue-600",
          visible: true,
          category: "climate",
          action: "auto",
        },
        {
          id: "fav_all_shutters",
          label: "All Shutters",
          icon: "Blinds",
          gradient: "from-indigo-500 to-purple-600",
          visible: true,
          category: "curtain",
          action: "auto",
        },
        {
          id: "fav_all_lights",
          label: "All Lights",
          icon: "Lightbulb",
          gradient: "from-amber-500 to-orange-600",
          visible: true,
          category: "light",
          action: "auto",
        },
        {
          id: "fav_all_switches",
          label: "All Switches",
          icon: "Zap",
          gradient: "from-emerald-500 to-teal-600",
          visible: true,
          category: "socket",
          action: "auto",
        },
      ],
      outdoorCity: "Smart Living HQ",
      outdoorTemp: 22.5,
      outdoorCondition: "Clear & Pleasant",
      outdoorHumidity: 46,
      outdoorAqi: 24,
      securityMode: "disarmed",
    });

    // Seed Devices
    await db.insert(devices).values([
      {
        id: "dev_light_ceiling_living",
        name: "Living Ceiling Chandelier",
        category: "light",
        roomId: "living_room",
        icon: "LampCeiling",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: true,
          brightness: 85,
          colorTemp: 4000,
          colorRgb: "#FFDE8A",
          presetScene: "Reading",
        },
        tuyaDeviceId: "bf38491823901a1",
        sortOrder: 1,
      },
      {
        id: "dev_light_strip_tv",
        name: "Ambient TV LED Strip",
        category: "light",
        roomId: "living_room",
        icon: "Sparkles",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: true,
          brightness: 75,
          colorTemp: 6000,
          colorRgb: "#00E5FF",
          presetScene: "Cyberpunk",
        },
        tuyaDeviceId: "bf90123849103b2",
        sortOrder: 2,
      },
      {
        id: "dev_ac_living",
        name: "Living Inverter AC",
        category: "climate",
        roomId: "living_room",
        icon: "AirVent",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: true,
          mode: "cool",
          targetTemp: 22.0,
          currentTemp: 23.4,
          fanSpeed: "mid",
          humidity: 48,
        },
        tuyaDeviceId: "bf82049102938c3",
        sortOrder: 3,
      },
      {
        id: "dev_curtain_living",
        name: "Motorized Curtains",
        category: "curtain",
        roomId: "living_room",
        icon: "Blinds",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          curtainPosition: 85,
          curtainState: "open",
        },
        tuyaDeviceId: "bf55910293849d4",
        sortOrder: 4,
      },
      {
        id: "dev_socket_media",
        name: "Media Center Smart Plug",
        category: "socket",
        roomId: "living_room",
        icon: "PlugZap",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: true,
          powerWatts: 184.2,
          energyKwh: 4.86,
          voltage: 224.5,
        },
        tuyaDeviceId: "bf77102938475e5",
        sortOrder: 5,
      },
      {
        id: "dev_vacuum_roborock",
        name: "Tuya Robot Vacuum S1",
        category: "vacuum",
        roomId: "living_room",
        icon: "Disc3",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: false,
          vacuumStatus: "docked",
          suctionLevel: "standard",
          battery: 98,
        },
        tuyaDeviceId: "bf44019283746f6",
        sortOrder: 6,
      },
      {
        id: "dev_light_bed_pendant",
        name: "Bedside Warm Pendant",
        category: "light",
        roomId: "bedroom",
        icon: "Lightbulb",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: false,
          brightness: 45,
          colorTemp: 2700,
          colorRgb: "#FFA726",
          presetScene: "Night",
        },
        tuyaDeviceId: "bf11234567890g7",
        sortOrder: 7,
      },
      {
        id: "dev_ac_bedroom",
        name: "Bedroom Whisper AC",
        category: "climate",
        roomId: "bedroom",
        icon: "ThermometerSnowflake",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: true,
          mode: "cool",
          targetTemp: 21.5,
          currentTemp: 22.0,
          fanSpeed: "low",
          humidity: 50,
        },
        tuyaDeviceId: "bf22345678901h8",
        sortOrder: 8,
      },
      {
        id: "dev_curtain_bedroom",
        name: "Blackout Roller Shades",
        category: "curtain",
        roomId: "bedroom",
        icon: "Blinds",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          curtainPosition: 100,
          curtainState: "open",
        },
        tuyaDeviceId: "bf33456789012i9",
        sortOrder: 9,
      },
      {
        id: "dev_air_purifier_bed",
        name: "Smart Air Purifier Pro",
        category: "fan",
        roomId: "bedroom",
        icon: "Wind",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: true,
          fanSpeed: "low",
          pm25: 11,
          co2: 435,
        },
        tuyaDeviceId: "bf44567890123j0",
        sortOrder: 10,
      },
      {
        id: "dev_light_kitchen_island",
        name: "Kitchen Island Spotlights",
        category: "light",
        roomId: "kitchen",
        icon: "SunMedium",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: true,
          brightness: 90,
          colorTemp: 5000,
          colorRgb: "#FFFFFF",
          presetScene: "Bright",
        },
        tuyaDeviceId: "bf55678901234k1",
        sortOrder: 11,
      },
      {
        id: "dev_socket_coffee",
        name: "Espresso Maker Outlet",
        category: "socket",
        roomId: "kitchen",
        icon: "Coffee",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: false,
          powerWatts: 0,
          energyKwh: 1.15,
          voltage: 226.1,
        },
        tuyaDeviceId: "bf66789012345l2",
        sortOrder: 12,
      },
      {
        id: "dev_light_balcony",
        name: "Balcony Bistro Lights",
        category: "light",
        roomId: "balcony",
        icon: "Flower2",
        protocol: "Bluetooth Mesh",
        online: true,
        state: {
          isOn: true,
          brightness: 65,
          colorRgb: "#FF8A65",
          presetScene: "Warm",
        },
        tuyaDeviceId: "bf77890123456m3",
        sortOrder: 13,
      },
      {
        id: "dev_curtain_balcony_awning",
        name: "Motorized Awning",
        category: "curtain",
        roomId: "balcony",
        icon: "SunDim",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          curtainPosition: 50,
          curtainState: "paused",
        },
        tuyaDeviceId: "bf88901234567n4",
        sortOrder: 14,
      },
      {
        id: "dev_door_lock",
        name: "Smart Biometric Door Lock",
        category: "lock",
        roomId: "entrance",
        icon: "Lock",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isLocked: true,
          battery: 92,
        },
        tuyaDeviceId: "bf99012345678o5",
        sortOrder: 15,
      },
      {
        id: "dev_camera_doorbell",
        name: "Front Door 2K Video Cam",
        category: "camera",
        roomId: "entrance",
        icon: "Camera",
        protocol: "Wi-Fi 6",
        online: true,
        state: {
          isOn: true,
          motionDetected: false,
          battery: 89,
        },
        tuyaDeviceId: "bf00123456789p6",
        sortOrder: 16,
      },
      {
        id: "dev_sensor_motion",
        name: "Corridor Motion Sensor",
        category: "sensor",
        roomId: "entrance",
        icon: "Eye",
        protocol: "Zigbee 3.0",
        online: true,
        state: {
          isOn: true,
          motionDetected: false,
          battery: 95,
        },
        tuyaDeviceId: "bf11234567890q7",
        sortOrder: 17,
      },
    ]);

    // Seed Scenes
    await db.insert(scenes).values([
      {
        id: "scene_good_morning",
        name: "Good Morning",
        description: "Open curtains, gentle warm lighting & start day",
        icon: "Sunrise",
        gradient: "from-amber-500 to-orange-500",
        actions: [
          { deviceId: "dev_curtain_living", stateChanges: { curtainPosition: 100, curtainState: "open" } },
          { deviceId: "dev_curtain_bedroom", stateChanges: { curtainPosition: 100, curtainState: "open" } },
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: true, brightness: 60, colorTemp: 3500 } },
          { deviceId: "dev_socket_coffee", stateChanges: { isOn: true } },
        ],
        sortOrder: 1,
      },
      {
        id: "scene_movie_night",
        name: "Cinema Night",
        description: "Dim lights, close curtains, cyber ambient lighting",
        icon: "Film",
        gradient: "from-indigo-600 to-purple-600",
        actions: [
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: false } },
          { deviceId: "dev_light_strip_tv", stateChanges: { isOn: true, brightness: 80, colorRgb: "#00E5FF" } },
          { deviceId: "dev_curtain_living", stateChanges: { curtainPosition: 0, curtainState: "closed" } },
          { deviceId: "dev_ac_living", stateChanges: { isOn: true, targetTemp: 21.0 } },
        ],
        sortOrder: 2,
      },
      {
        id: "scene_cozy_dinner",
        name: "Cozy Dinner",
        description: "Warm glow in dining area, relaxed balcony lights",
        icon: "Wine",
        gradient: "from-rose-500 to-pink-600",
        actions: [
          { deviceId: "dev_light_kitchen_island", stateChanges: { isOn: true, brightness: 70, colorTemp: 3000 } },
          { deviceId: "dev_light_balcony", stateChanges: { isOn: true, brightness: 80 } },
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: true, brightness: 35, colorTemp: 2700 } },
        ],
        sortOrder: 3,
      },
      {
        id: "scene_away_guard",
        name: "Leave Home",
        description: "Turn off all lights, close shades, arm security",
        icon: "ShieldAlert",
        gradient: "from-emerald-600 to-teal-700",
        actions: [
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: false } },
          { deviceId: "dev_light_strip_tv", stateChanges: { isOn: false } },
          { deviceId: "dev_light_bed_pendant", stateChanges: { isOn: false } },
          { deviceId: "dev_light_kitchen_island", stateChanges: { isOn: false } },
          { deviceId: "dev_light_balcony", stateChanges: { isOn: false } },
          { deviceId: "dev_socket_coffee", stateChanges: { isOn: false } },
          { deviceId: "dev_door_lock", stateChanges: { isLocked: true } },
        ],
        sortOrder: 4,
      },
      {
        id: "scene_relax_reading",
        name: "Relax & Read",
        description: "Optimal warm reading light, low whisper air",
        icon: "BookOpen",
        gradient: "from-teal-500 to-cyan-600",
        actions: [
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: true, brightness: 45, colorTemp: 3200 } },
          { deviceId: "dev_air_purifier_bed", stateChanges: { isOn: true, fanSpeed: "low" } },
        ],
        sortOrder: 5,
      },
      {
        id: "scene_all_off",
        name: "All Devices Off",
        description: "Quick master shut-off for lights and appliances",
        icon: "Power",
        gradient: "from-zinc-700 to-slate-800",
        actions: [
          { deviceId: "dev_light_ceiling_living", stateChanges: { isOn: false } },
          { deviceId: "dev_light_strip_tv", stateChanges: { isOn: false } },
          { deviceId: "dev_light_bed_pendant", stateChanges: { isOn: false } },
          { deviceId: "dev_light_kitchen_island", stateChanges: { isOn: false } },
          { deviceId: "dev_light_balcony", stateChanges: { isOn: false } },
          { deviceId: "dev_ac_living", stateChanges: { isOn: false } },
          { deviceId: "dev_ac_bedroom", stateChanges: { isOn: false } },
        ],
        sortOrder: 6,
      },
    ]);

    // Seed Activity Logs
    await db.insert(activityLogs).values([
      {
        deviceId: "dev_door_lock",
        deviceName: "Smart Biometric Door Lock",
        action: "Locked automatically by auto-secure rule",
        type: "security",
        source: "Wall Panel Kiosk",
      },
      {
        deviceId: "dev_ac_living",
        deviceName: "Living Inverter AC",
        action: "Target temperature set to 22.0°C (Cool mode)",
        type: "device",
        source: "Wall Tablet",
      },
      {
        deviceId: "dev_light_strip_tv",
        deviceName: "Ambient TV LED Strip",
        action: "Turned ON - Cyberpunk preset activated",
        type: "device",
        source: "Wall Tablet",
      },
      {
        deviceName: "Tuya Central Gateway",
        action: "Mesh Zigbee network synced 17 devices OK",
        type: "system",
        source: "Tuya Cloud",
      },
    ]);
  } catch (err) {
    console.error("Error seeding database:", err);
  }
}
